# thdihan

name: Deploy to Remote Server
on:
    push:
        branches:
            - main
jobs:
    deploy:
        name: Deploy to Remote Server
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4.2.2

            - name: Setup SSH key
              uses: webfactory/ssh-agent@v0.9.0
              with:
                  ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
                  ssh-public-key: ${{ secrets.SSH_PUBLIC_KEY }}

            - name: Execute Remote Commands
              run: |
                  ssh -o StrictHostKeyChecking=no root@139.59.41.51 -p 22 << 'EOF'
                    cd /root/thdihan.dev/
                    git pull
                    pnpm i
                    pnpm build
                    sudo systemctl restart thdihan_dev.service
                    exit
                  EOF
              shell: bash
